language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t ahuakau/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true ahuakau/docker-react npm run test